refactoring sdk
friendliai/periflow-python-sdk pull request #24
Opened 2022-04-08 03:36 UTC by ktaebum

2022-04-08 04:32 UTC, ktaebum commented
![스크린샷 2022-04-08 오후 1 31 49](https://user-images.githubusercontent.com/19629048/162364030-45372b47-4f42-4dce-87d7-9e838475de1d.png)

Now accept custom checkpoint file name 🙂

2022-04-20 05:23 UTC, kooyunmo requested changes

2022-04-20 05:23 UTC, kooyunmo commented on src/periflow_sdk/utils.py
> +    return wrapper
```suggestion
def check_initialized(func):
    @functools.wraps
    def wrapper(training_manager, *args, **kwargs):
        assert training_manager.has_initialized, f'{func.__name__} must be called after pf.init()!'
        return func(*args, **kwargs)
    return wrapper
```

To preserve the name and docstrings of decorated function, `wraps` needs to decorate the inner function `wrapper`.

2022-04-21 08:31 UTC, kooyunmo approved these changes

2022-04-21 08:31 UTC, merged