add readme
friendliai/periflow-python-sdk pull request #32
Opened 2022-04-26 07:44 UTC by ktaebum

2022-04-26 08:55 UTC, Algy approved these changes

2022-04-26 10:48 UTC, kooyunmo commented on README.md
> +```
```sh

2022-04-26 10:54 UTC, kooyunmo requested changes
Please add a language specification for the code blocks

2022-04-26 10:54 UTC, kooyunmo commented on README.md
> +```
```suggestion
```sh
```

2022-04-26 10:54 UTC, kooyunmo commented on README.md
>  ```
```suggestion
```sh
```

2022-04-26 10:54 UTC, kooyunmo commented on README.md
> +```
```suggestion
```python
```

2022-04-26 10:54 UTC, kooyunmo commented on README.md
> +```
```suggestion
```python
pf.init(total_train_steps: int, local_log_name: Optional[str] = None) -> None
```
```

2022-04-26 10:54 UTC, kooyunmo commented on README.md
> +```
```suggestion
```python
pf.start_step() -> None
```
```

2022-04-26 10:54 UTC, kooyunmo commented on README.md
> +```
```suggestion
```python
pf.end_step() -> None
```
```

2022-04-26 10:54 UTC, kooyunmo commented on README.md
> +```
```suggestion
```python
with pf.train_step():
    # your training step code
```
```

2022-04-26 10:54 UTC, kooyunmo commented on README.md
> +```
```suggestion
```python
4. pf.upload_checkpoint() -> None
```
```

2022-04-26 10:54 UTC, kooyunmo commented on README.md
> +```
```suggestion
```python
import torch

...
if torch.distributed.get_rank() == 0:
    torch.save(state_dict, CKPT_PATH)
    pf.upload_checkpoint()
```
```

2022-04-26 10:54 UTC, kooyunmo commented on README.md
> +```
```suggestion
```python
```

2022-04-26 10:54 UTC, kooyunmo commented on README.md
> +```
```suggestion
```python
pf.metric(msg: Dict[str, JSONValue]) -> None
```
```

2022-04-26 11:00 UTC, kooyunmo commented
For me, the code block located inside a sentence looks weird. Can you please complete the sentences and put the example code block after each sentence?

2022-04-27 04:29 UTC, Algy approved these changes

2022-04-27 04:30 UTC, kooyunmo approved these changes

2022-04-27 04:31 UTC, merged