Huggingface LoRA finetuning example
friendliai/periflow-python-sdk pull request #49
Opened 2022-07-28 03:58 UTC by footprinthere

- Added huggingface transformers example, where models are finetuned using [LoRA](https://github.com/microsoft/LoRA) method.

- Renamed incorrectly-named classes (`Periflow...` -> `PeriFlow...`)

- ***Please check if the directory structure I made so far is appropriate.***

2022-08-22 08:25 UTC, Hyeonmin-Ha requested changes

2022-08-22 08:25 UTC, Hyeonmin-Ha commented on examples/huggingface/lora_bert_finetuning/requirements.txt
> +accelerate==0.3.0
Do we really need all of these packages??
Or this is the copy of your env?

2022-08-22 08:25 UTC, Hyeonmin-Ha commented on examples/huggingface/lora_bert_finetuning/run_glue.py
> +#!/usr/bin/env python
I think we'd better upload the original one (as [in the MLM example](https://github.com/friendliai/periflow-python-sdk/blob/example/examples/huggingface/bert_masked_language_modeling/original/run_mlm.py)), so that people can easily catch the difference between the original and PeriFlow version.

2022-08-23 07:58 UTC, footprinthere commented
All comments reflected.

2022-08-23 08:06 UTC, merged