Huggingface speech recognition finetuning examples
friendliai/periflow-python-sdk pull request #50
Opened 2022-08-03 05:05 UTC by footprinthere

2022-08-22 08:40 UTC, Hyeonmin-Ha commented
We need to update the directory structure.
Currently, language-related HF examples are in `examples/huggingface`.
But, speech-related HF examples in `examples/hug../speech_recognition`.
One way to resolve this will be move lang-related HF examples to `examples/hug../language`.

2022-08-22 08:55 UTC, Hyeonmin-Ha requested changes

2022-08-22 08:55 UTC, Hyeonmin-Ha commented on examples/huggingface/speech_recognition/ctc/script.sh
> +mv ../data/common_voice ../common_voice
Remove these lines, and set `dataset_cache_dir` to `/workspace/data`

2022-08-22 08:55 UTC, Hyeonmin-Ha commented on examples/huggingface/speech_recognition/ctc/script.sh
> +pip install git+https://github.com/huggingface/transformers
I think we need to specify the transformers version too, if we use specific torch version.

2022-08-22 08:55 UTC, Hyeonmin-Ha commented on examples/huggingface/speech_recognition/seq2seq/script.sh
> +pip install git+https://github.com/huggingface/transformers
Same comment

2022-08-22 08:55 UTC, Hyeonmin-Ha commented on examples/huggingface/speech_recognition/seq2seq/run_speech_recognition_seq2seq.py
> +def prepare_model(model_path):
How about move this function to a separated script (`prepare.py` for example) for consistency with the original example?

2022-08-22 09:13 UTC, Hyeonmin-Ha requested changes

2022-08-22 09:13 UTC, Hyeonmin-Ha commented on examples/huggingface/speech_recognition/ctc/script.sh
> +pip install git+https://github.com/huggingface/transformers
And move this to `requirements.txt`

2022-08-22 09:13 UTC, Hyeonmin-Ha commented on examples/huggingface/speech_recognition/ctc/script.sh
> +pip install git+https://github.com/huggingface/transformers
Do we need torch 1.10? `requirements.txt` says torch>=1.5.

2022-08-23 06:00 UTC, footprinthere commented on examples/huggingface/speech_recognition/ctc/script.sh
> +pip install git+https://github.com/huggingface/transformers
1. Specifying any version of `transformers` results to an ImportError:
    ```
    ImportError: : This example requires a source install from HuggingFace Transformers (see `https://huggingface.co/transformers/installation.html#installing-from-source`), but the version found is 4.21.1.
    ```
    As the [docs](https://huggingface.co/docs/transformers/installation#install-from-source) says, it seems that it is the only way to install `transformers` directory from git source.

2. Moved to `requirements.txt`.

3. Similar to the problem that happened in `MMF` example. Without explicitly installing `torch`, the program would result to an NCCL error and fail.

2022-08-23 06:17 UTC, footprinthere commented on examples/huggingface/speech_recognition/ctc/script.sh
> +mv ../data/common_voice ../common_voice
That results to an error in this example.
```
formats: can't open input file `downloads/extracted/14fbc5e0dd3e55b1771c258791de7514a56105ebe0f58e6aec60cae718283064/cv-corpus-6.1-2020-12-11/hi/clips/common_voice_hi_23795238.mp3': No such file or directory
```
It seems that regardless of the path specified by `dataset_cache_dir`, the program always tries to find datasets in the directory where the program code is placed. I have tried to find out why but failed.

2022-08-23 06:33 UTC, footprinthere commented on examples/huggingface/speech_recognition/seq2seq/run_speech_recognition_seq2seq.py
> +def prepare_model(model_path):
Comment reflected.

2022-08-23 07:35 UTC, footprinthere commented on examples/huggingface/speech_recognition/seq2seq/script.sh
> +pip install git+https://github.com/huggingface/transformers
Please see the comment above.

2022-08-23 08:10 UTC, Hyeonmin-Ha commented on examples/huggingface/speech_recognition/ctc/script.sh
> +pip install git+https://github.com/huggingface/transformers
Have you tried `pip install git+https://github.com/django/django.git@<tag name>` where the tag name specifies the release you are using?

2022-08-23 08:20 UTC, Hyeonmin-Ha requested changes

2022-08-23 08:20 UTC, Hyeonmin-Ha commented on examples/huggingface/speech/speech_recognition_ctc/script.sh
> +rm -rf data
What does this actually remove?
This is dependent with the docker image we use, which specifies the start point.

2022-08-23 08:20 UTC, Hyeonmin-Ha commented on examples/huggingface/speech/speech_recognition_seq2seq/model.py
> +from transformers import (
Please rename this script to `prepare_model.py`.

2022-08-23 08:20 UTC, Hyeonmin-Ha commented on examples/huggingface/speech/speech_recognition_seq2seq/run_speech_recognition_seq2seq.py
> +
Please run `prepare_model` separately with this script.
i.e, Run `prepare_model.py`, and then run this script in `script.sh`. (As in the original example)
The reason for this is that we'd like to keep the original code.

2022-08-23 08:25 UTC, Hyeonmin-Ha commented on examples/huggingface/speech_recognition/ctc/script.sh
> +mv ../data/common_voice ../common_voice
It seems that [eval dataset loading](https://github.com/friendliai/periflow-python-sdk/blob/example-speech/examples/huggingface/speech/speech_recognition_ctc/run_speech_recognition_ctc.py#L457) doesn't use `cache_dir`.
Please try fixing this.

2022-08-23 08:26 UTC, Hyeonmin-Ha commented
Please resolve the conflict.

2022-08-24 01:27 UTC, footprinthere commented on examples/huggingface/speech_recognition/ctc/script.sh
> +pip install git+https://github.com/huggingface/transformers
The [programs](https://github.com/friendliai/periflow-python-sdk/blob/70db9c177f85cc0a1158216b781b7a0bbcf8cfd3/examples/huggingface/speech/speech_recognition_ctc/run_speech_recognition_ctc.py#L58) says we need version `4.22.0.dev0`, but it seems that the `transformers` [github repository](https://github.com/huggingface/transformers/tags) does not support this version as a release or a tag.

2022-08-24 01:28 UTC, footprinthere commented on examples/huggingface/speech/speech_recognition_seq2seq/run_speech_recognition_seq2seq.py
> +
Comment reflected.

2022-08-24 01:50 UTC, footprinthere commented on examples/huggingface/speech_recognition/ctc/script.sh
> +mv ../data/common_voice ../common_voice
Or you can check the job log of ___1967___.

2022-08-24 05:12 UTC, Hyeonmin-Ha commented on examples/huggingface/speech_recognition/ctc/script.sh
> +pip install git+https://github.com/huggingface/transformers
I think we are using too recent example code, which is before the release.
The latest transformers version is 4.21, so we cannot meet the requirement with the stable version.
Let's skip this issue and resolve later.

2022-08-24 06:04 UTC, Hyeonmin-Ha commented on examples/huggingface/speech_recognition/ctc/script.sh
> +pip install git+https://github.com/huggingface/transformers
And as you said in the other PR, our docker image uses CUDA 11.6, so we should use torch that support the CUDA version. (i.e, torch 1.12)

2022-08-24 09:06 UTC, footprinthere commented
All problems solved. @Hyeonmin-Ha

2022-08-24 10:22 UTC, Hyeonmin-Ha approved these changes

2022-08-24 10:22 UTC, merged